def que():
    que_list=["How many continents are there?",
  " What is the capital of India?",
   "NG mei kaun se course padhaya jaata hai?"]
que()
def _opt():
    ["Four", "Nine", "Seven", "Eight"],
    ["Chandigarh", "Bhopal", "Chennai", "Delhi"],
    ["Software Engineering", "Counseling", "Tourism", "Agriculture"]
solution_list = [3, 4, 1]
_opt()


def lifeline():
    ["(2)nine", "(3)seven"],
    ["(2) bhopal","(4)delhi"],
    ["(1)software engineering","(4)agriculture"]
print("WELCOME TO KBC🙏🙏")
lifeline()
   
    i=0
    money=0
    c=0
    while i<len(question_list):
         print(question_list[i])
         j=0
    # while j<len(options_list[i]):
    #      d=options_list[i][j]
    #     print(d)
    #     j=j+1
    # if c<2:
    #     user_input= input("do you using life line:")
    #     if user_input=="yes":
    #         c=c+1
    #         print("5050",lifeline[i])
    # else:
    #     print("sorry!,you can't use lifeline because you already used lifeline,")
    # b=int(input("choose the answer:"))  
    # if b==solution_list[i]:
    #     money+=5000
    #     print("your answer is correct")
    #     print("you win RS./-",money)
    # else:
    #     print("your answer is wrong")  
    #     break
    # i=i+1
